apiVersion: v1
kind: Service
metadata:
  name: node-hostname
  labels:
    app: node-hostname
spec:
  selector:
    app: node-hostname
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
