name: CI/CD

# Exclude the workflows to run on changes to the helm chart
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Docker environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies (optional, if needed by Dockerfile)
        run: npm install

  push:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node-hostname:${{github.run_id}}


  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: Update tag in Helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/go-web-app-chart/values.yaml

    - name: Commit and push changes
      run: |
        git config --global user.email "naveenshetty0812@gmail.com"
        git config --global user.name "Naveen"
        git add helm/node-hostname-chart/values.yaml
        git commit -m "Update tag in Helm chart"
        git push
  deploy:
    runs-on: ubuntu-latest
    needs: update-newtag-in-helm-chart
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
          fetch-depth: 0

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Adjust the AWS region to your cluster's region

      - name: Set up kubectl
        run: |
          curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.5/2021-10-11/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin

      - name: Set up EKS kubeconfig
        run: |
          aws eks --region us-east-1 update-kubeconfig --name flask-cluster

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          helm version

      - name: Delete existing resources if they exist
        run: |
          kubectl delete deployment node-hostname --ignore-not-found=true
          kubectl delete service node-hostname --ignore-not-found=true
          kubectl delete ingress node-hostname --ignore-not-found=true

      - name: Deploy to EKS using Helm
        run: |
          helm upgrade --install node-hostname helm/node-hostname-chart --namespace default --set image.tag=${{github.run_id}}
